platform :ios, '7.0'
pod 'AFNetworking'
pod 'MJRefresh'
pod 'MBProgressHUD'
pod 'JZLocationConverter'

#其他缓冲相关
#pod 'Toast'
#pod 'SVProgressHUD'
#JSON->NSObject
#pod 'MJExtension' 
#新浪微博
#pod "WeiboSDK", :git => "https://github.com/sinaweibosdk/weibo_ios_sdk"